version: "3.9"

services:

  php74-cli:
    image: php:7.4-cli
    volumes:
      - ..:/app/
    working_dir: /app

  php80-cli:
    image: php:8.0-cli
    volumes:
      - ..:/app/
    working_dir: /app

  php81-cli:
    build: ./php81-cli/
    volumes:
      - ..:/app
      - ../logs:/var/log/xdebug
    working_dir: /app
